### ISSUE TITLE
Copy&Paste mistake in readme?

### ISSUE THREAD

**Issue by SISheogorath** [LorbusChris/greenboot#25]
The readme lists two examples, the wanted check for systemd and the required check for systemd. From reading them they look exactly the same to me, when it comes to the fields that are actually relevant for Systemd. But I guess this is due to a copy and paste mistake?

The last example should be `WantedBy=boot-complete.target` instead of being also `RequiredBy`, right? Or is there something I'm missing?

**Comment by LorbusChris** [comment]
oopsies, you're absolutely right.
