### ISSUE TITLE
Notification scripts should update MOTD

### ISSUE THREAD

**Issue by LorbusChris** [LorbusChris/greenboot#8]

**Comment by LorbusChris** [comment]
@dustymabe updating the motd could be done using a red/green script, or directly in the respective service unit using `ExecStartPost`. Doing either of them requires PAM v1.3.1.

Using a script, we could move that dependency to the `greenboot-notifications`/`greenboot-motd` package.
Putting it in the service unit would mean we need PAM for every install.
I wouldn't mind the extra dep and would happily add it to the service and remove the entire `-notifications` package, but what's preferable to you?

Thanks for pointing me to https://cockpit-project.org/blog/cockpit-169.html btw :+1: 
(relevant code's here: https://github.com/cockpit-project/cockpit/commit/da6f78bdf0e0fbc8b9a1bb29a7809efb39876f6f)

**Comment by dustymabe** [comment]
could we have a `greenboot-motd` package that updates the greenboot status (either failed or succeeded) in motd. i.e. it would update motd whether boot failed or succeeded and it would also be optional since it would be in a separate package people could choose to install or not install.
