### ISSUE TITLE
Submit Fedora Package Review

### ISSUE THREAD

**Issue by LorbusChris** [LorbusChris/greenboot#9]

**Comment by nullr0ute** [comment]
This should read "Package and submit Fedora review" from there you'll get a fedora git repo, and can then build it in koji. We can then add it to IoT composes for further testing.

https://fedoraproject.org/wiki/Packaging:Guidelines?rd=Packaging/Guidelines

**Comment by nullr0ute** [comment]
This should read "Package and submit Fedora review" from there you'll get a fedora git repo, and can then build it in koji. We can then add it to IoT composes for further testing.

https://fedoraproject.org/wiki/Packaging:Guidelines?rd=Packaging/Guidelines

**Comment by LorbusChris** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1615895
